# Generated by Django 6.0.3 on 2026-03-12 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Image', models.ImageField(upload_to='images/')),
                ('Audio', models.FileField(upload_to='audio/')),
                ('Video', models.FileField(upload_to='video/')),
            ],
        ),
    ]
