# Generated by Django 6.0.3 on 2026-03-12 10:36

import cloudinary_storage.storage
import cloudinary_storage.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='Audio',
            field=models.FileField(storage=cloudinary_storage.storage.RawMediaCloudinaryStorage(), upload_to='audio/'),
        ),
        migrations.AlterField(
            model_name='media',
            name='Image',
            field=models.ImageField(storage=cloudinary_storage.storage.MediaCloudinaryStorage(), upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='media',
            name='Video',
            field=models.FileField(storage=cloudinary_storage.storage.VideoMediaCloudinaryStorage(), upload_to='video/', validators=[cloudinary_storage.validators.validate_video]),
        ),
    ]
